# NumPy

NumPy is a Linear Algebra Library for Python. Almost all of the libraries in the PyData ecosystem are built ontop of NumPy, making it one of the most important python libraries to be familiar with.

Numpy is also incredibly fast, as it has bindings to C libraries, which is what is called a `low-level` language.

For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists) post.

<hr>
<br>
<br>

## 1. Using NumPy

The anaconda distribution of python comes with the NumPy library pre-installed, so all we have to do is import it!
<br>
You can import any pre-installed library, as such:

#### Import Format in python: 
```python
import library_name as alias
```

#### Import `numpy`

```python
import numpy as np
```

In [0]:
import numpy as np

<br>

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: arrays, and number generation. Let's start by discussing arrays.

<hr>
<br>
<br>

# 2. Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional arrays and matrices are 2-dimensional, e.g., a nested list. We will be focusing our efforts on 1-D Arrays!

Let's begin our introduction by exploring how to create NumPy arrays.

<br>

## A. Creating NumPy Arrays

### From a Python List

We can create a numpy array by passing a python `list` into the `NumPy` method: `np.array()`
<hr>

``` python
my_list = [1,2,3]
print(my_list)

my_array = np.array(my_list)
print(my_array)
```

<hr>

In [2]:
my_list = [1,2,3]
print(my_list)

my_array = np.array(my_list)
print(my_array)

[1, 2, 3]
[1 2 3]


<hr>
<br>
<br>

## B. Array Attributes and Methods

Let's discuss some useful attributes and methods of an array:

### Numpy array `.shape` attribute

**Attribute:** Returns an array's shape, all NumPy arrays have this attribute in common.

#### One dimensional numpy array

A one dimensional array will have many rows but only one column per row.

```python
one_dimensional_list = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
one_dimensional_numpy_array = np.array(one_dimensional_list)

print("shape of one_dimensional_numpy_array:", one_dimensional_numpy_array.shape)
print(one_dimensional_numpy_array)
```

In [10]:
one_dimensional_list = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
one_dimensional_numpy_array = np.array(one_dimensional_list)

print("shape of one_dimensional_numpy_array:", one_dimensional_numpy_array.shape)
print(one_dimensional_numpy_array)

shape of one_dimensional_numpy_array: (16,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


The shape (16,) signifies that this numpy array has 16 rows, each with 1 column per row

#### Multiple dimensional numpy array
A multiple dimensional array will have many rows, each row having more than one column.


```python
multi_dimensional_list = [[1,2], [3,4], [5,6]]
multi_dimensional_numpy_array = np.array(multi_dimensional_list)

print("shape of multi_dimensional_numpy_array:", multi_dimensional_numpy_array.shape)
print(multi_dimensional_numpy_array)
```

In [9]:
multi_dimensional_list = [[1,2], [3,4], [5,6]]
multi_dimensional_numpy_array = np.array(multi_dimensional_list)

print("shape of multi_dimensional_numpy_array:", multi_dimensional_numpy_array.shape)
print(multi_dimensional_numpy_array)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


The shape (3,2) signifies that this numpy array has 3 rows, each with 2 columns per row


<br>

### `.dtype`

**Attribute:** Returns the *single* data type present in numpy array reguardless of the numpy array being one or multi dimensiona;:

**Note**: Numpy Arrays can only contain a *single* datatype. Meaning you can't have two different type of values inside a single numpy array.


```python
print(one_dimensional_numpy_array.dtype)
```

In [12]:
print(one_dimensional_numpy_array.dtype)

int64


```python
print(multi_dimensional_numpy_array.dtype)
```

In [13]:
print(multi_dimensional_numpy_array.dtype)

int64


<br>

### `.reshape()`
**Method:** Returns an array containing the same data with a new shape.

**Note:** Multiply the shape of an array together, to find out what other shapes are available. Any factor of the shape's rows multiplied by the columns can be a possible shape of the numpy array.
<br>
Ex: a `1x12` vector can be a `12x1` vector or even a `3x4` or `4x3` Matrix, etc... 

```python
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr)
print("arr shape:", arr.shape)

print() # print a blank line

# convert a 1x16 vector to a 16 x 1 matrix
arr_16_1 = arr.reshape(1,16)
print(arr_16_1)
print("arr_16_1 shape:", arr_16_1.shape)
```

In [19]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr)
print("arr shape:", arr.shape)

print() # print a blank line

# convert a 1x16 vector to a 16 x 1 matrix
arr_16_1 = arr.reshape(1,16)
print(arr_16_1)
print("arr_16_1 shape:", arr_16_1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
arr shape: (16,)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
arr_16_1 shape: (1, 16)


```python
arr_1_16 = arr.reshape(16,1)

# 1 x 16 matrix
print(arr_1_16.shape)
print(arr_1_16)
```

In [20]:
arr_1_16 = arr.reshape(16,1)

# 1 x 16 matrix
print(arr_1_16.shape)
print(arr_1_16)

(16, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


<br>
<br>

### `.max()`, `.min()`, `.argmax()` and `.argmin()`

These are useful methods for finding max or min values. Or to find their respective index locations using argmin or argmax

**Note:** We can either invoke the methods through using the dot notation on the numpy array as such: 

```python
numpy_array = np.array([1,2,3])
numpy_array.max()
```

**Or** we can invoke the method off of the numpy library reference `np` and passing in the numpy array as the first argument like so:

```python
numpy_array = np.array([1,2,3])
np.max(numpy_array)
```


<br>

####Create a numpy array

```python
# Generate an array of length 10, randomly selected from the integers between [1 (inclusive), 20 (non-inclusive)].
some_array = np.array([8, 9, 5, 16, 8, 6, 15, 10, 6, 17])
```

In [0]:
# Generate an array of length 10, randomly selected from the integers between [1 (inclusive), 20 (non-inclusive)].
some_array = np.array([8, 9, 5, 16, 8, 6, 15, 10, 6, 17])

#### `.max()` will return the max value in the numpy array

```python
print(some_array.max())

# Or
print(np.max(some_array))
```

In [27]:
print(some_array.max())
 
# Or
print(np.max(some_array))

17
17


#### `.argmax()` will return the index of the max value in the numpy array

```python
print(some_array.argmax())

# or 
print(np.argmax(some_array))
```

In [28]:
print(some_array.argmax())
 
# or 
print(np.argmax(some_array))

9
9


#### `.min()` will return the minimum value in the numpy array

```python
print(some_array.min())

# or
print(np.min(some_array))
```

In [29]:
print(some_array.min())

# or
print(np.min(some_array))

5
5


#### `.argmin()` will return the index of the minimum value in the numpy array

```python
print(some_array.argmin())

# or 
print(np.argmin(some_array))
```

In [30]:
print(some_array.argmin())

# or 
print(np.argmin(some_array))

2
2


<hr>
<br>
<br>

## C. NumPy Number Generation Functions

There are lots of built-in ways to generate Arrays

### `np.arange()`

Return evenly spaced values within a given interval.

np.arange(start, stop, increment)

**Note:** 
- start is inclusive  
- stop is exclusive
- if increment is not specified then it will be 1 automatically 

```python
print(np.arange(1950,1978))
```

In [0]:
print(np.arange(1950,1978))

[1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963
 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977]


```python
print(np.arange(1950,1978,2))
```

In [0]:
print(np.arange(1950,1978,2))

[1950 1952 1954 1956 1958 1960 1962 1964 1966 1968 1970 1972 1974 1976]


<br>

### `.zeros()` and `.ones()`

Generate arrays of zeros or ones

```python
three_zeros = np.zeros(3)
print(three_zeros)
```

In [0]:
three_zeros = np.zeros(3)
print(three_zeros)

[0. 0. 0.]


### **The one difference between python lists and numpy arrays is that we can do element wise operations with numpy arrays.** 
Meaning for example we can add 5 to all elements in the numpy array like such:

```python
five_fives = np.zeros(5) + 5
print(five_fives)
```

In [0]:
five_fives = np.zeros(5) + 5
print(five_fives)

[5. 5. 5. 5. 5.]


```python
one_hundred_ones = np.ones(100)
print(one_hundred_ones)
```

In [0]:
one_hundred_ones = np.ones(100)
print(one_hundred_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


```python
ten_hundreds = np.ones(10) * 100
print(ten_hundreds)
```

In [0]:
ten_hundreds = np.ones(10) * 100
print(ten_hundreds)

[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]


<br>

### `.linspace()`
Return evenly spaced numbers over a specified interval.

linspace stands for `linearly spaced vectors`

```python
print(np.linspace(1,10,100))
```

In [0]:
print(np.linspace(1,10,100))

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

```python
print(np.linspace(0,10,50))
```

In [0]:
print(np.linspace(0,10,50))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


<hr>
<br>
<br>

## D. NumPy Random Number Generation Module

Numpy also has lots of ways to create random number arrays through its `random` module:

We must reference the random module like so:

<hr>

```python
np.random.randint?
```

<hr>

In [0]:
np.random.randint?

<br>

### `.random.rand()`
Create an array of the given shape and populate it with
random samples from a **uniform distribution**
over ``[0, 1)``.

```python
print(np.random.rand(5))
```

In [0]:
print(np.random.rand(5))

[0.87619846 0.05570262 0.32194126 0.538975   0.22948761]


<br>

### `.random.randn()`

Return a sample (or samples) from the **standard normal** distribution over ~`(-3, 3)`

```python
print(np.random.randn(10))
```

In [0]:
print(np.random.randn(10))

[-2.11816914  1.51222452 -0.87957289  0.6198961   0.99063271  0.29709562
 -0.09397857  1.62820862 -0.29163391 -0.31911559]


<br>

### `.random.randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

```python
print(np.random.randint(1,100))
```

In [0]:
print(np.random.randint(1,100,5))

[56 70 65 15 99]


```python
print(np.random.randint(low=1, high=100, size=10))
```

In [0]:
print(np.random.randint( high=100,low=1, size=10))

[59 53 24 53  3 57 98 63 75 34]
