# NumPy Array Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

## <span style="color:blue"> 1. Import `numpy` with the `alias` `np`</span>

<hr>
<br>
<br>

## <span style="color:blue"> 2. Create a numpy array out of a python list </span>

### A. Numpy Arrays: `int` datatype

#### Create a python list containing elements of `int` datatype and store it in a variable called `py_list`

#### Convert `py_list` into `numpy` array and store in `np_arr`

#### Grab the `type` of `np_arr` and `print` to screen. 

#### Print `np_arr` to screen... Take note of the `int` values.

#### Print `shape` of `np_arr` to screen. 

<br>

### B. Numpy Arrays: `int` and `str` mixed datatype

#### Change `py_list` to include a `string`

#### Convert `py_list`, into `numpy` array and store in `np_arr`

#### Grab the `type` of `np_arr` and `print` to screen. 

#### Print `np_arr` to screen... notice something different about the `int` values?

#### Print `shape` of `np_arr` to screen. Notice the change?

<hr>
<br>
<br>

## <span style="color:blue"> 3. Create an array of 10 zeros, store in variable `zero10`. </span>

```python
[0 0 0 0 0 0 0 0 0 0]
```

#### Grab the `shape` of `zero10` and store it in `zero10shp` 

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [0]:
np.testing.assert_array_equal(zero10, np.array([0,0,0,0,0,0,0,0,0,0]))

In [0]:
assert zero10shp == (10,)

<hr>
<br>
<br>

## <span style="color:blue"> 4. Create an array of 10 ones, store in variable `one10` </span>
```python
[1 1 1 1 1 1 1 1 1 1]
```

#### Grab the `shape` of `one10` and store it in `one10shp` 

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [0]:
np.testing.assert_array_equal(one10, np.array([1,1,1,1,1,1,1,1,1,1]))

In [0]:
assert one10shp == (10,)

<hr>
<br>
<br>

## <span style="color:blue"> 5. Create an array of 10 fives, store it in variable `five10` </span>

```python
[5 5 5 5 5 5 5 5 5 5]
```

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [0]:
np.testing.assert_array_equal(five10, np.array([5,5,5,5,5,5,5,5,5,5]))

<hr>
<br>
<br>

## <span style="color:blue"> 6. Create an array of the integers from 10 to 50, store in variable `ints1050` </span>

```python
[10 11 12 13 ... 48 49 50]
```

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [0]:
np.testing.assert_array_equal(ints1050, np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50]))

<hr>
<br>
<br>

## <span style="color:blue"> 7. Create an array of only the *even* integers from 10 to 50, store in variable `even_ints1050` </span>

```python
[10 12 14 16 ... 44 46 48 50]
```

#### Test Yourself:

**Remember:** If the cells below run without an **AssertionError**, this means that you've completed the task correctly —**otherwise**, you have made a mistake and must alter your code above, then try to run Assert cells once again.

In [0]:
np.testing.assert_array_equal(even_ints1050, np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50]))

<hr>
<br>
<br>

## <span style="color:blue"> 8. Generate an array of 20 *linearly spaced points* between 0 and 1, output array must include both 0 and 1 —store it in `lin20` </span>

```python
[0 ... 1]
```

In [0]:
np.testing.assert_array_almost_equal(lin20, np.array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]))

<hr>
<br>
<br>

## <span style="color:blue"> 9. Use NumPy's Random Module to generate a random number between 0 and 1 </span>

Some ex results: `[0.55288314]`, `[0.20471546]`, etc

**No Assertion Test** for this one, as **your answer will be randomly generated!**

<hr>
<br>
<br>

## <span style="color:blue"> 10. Use NumPy's Random Module to generate an array of 25 random numbers sampled from the *Standard Normal Distribution*, store it in variable `ran_arr`. </span>

The Standard Normal Distribution is a distribution of numbers between ~`-3` and `3` where the `mean` is `0`.  

#### Calculate the `max()` and `argmax()`, store in variables `mx` and `argmx`. `print` your results, do they make sense?

#### Calculate the `min()` and `argmin()`, store in variables `mn` and `argmn`. `print` your results, do they make sense?

**No Assertion Test** for this one, as **your answer will be randomly generated!**