# NumPy Operations

#### Import numpy

In [0]:
import numpy as np

We will use `arr` to complete this notebook run the below cell.

In [2]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


<br>

## Elementwise Operations

With numpy you can easily perform array with array arithmetic, or scalar with array arithmetic. 

**References:**

- [Numpy array operations](https://scipy-lectures.org/intro/numpy/operations.html)

- [Numpy methods and attributes](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html)

Let's see some examples:

```python
print(arr + arr)
```

In [3]:
print(arr + arr)

[ 0  2  4  6  8 10 12 14 16 18]


```python
print(arr - arr)
```

In [4]:
print(arr - arr)

[0 0 0 0 0 0 0 0 0 0]


```python
# Warning on division by zero, but NOT an error!
# Just replaced with nan
print(arr / arr)
```

In [5]:
print(arr / arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


```python
# Also warning, but not an error, instead infinity as `np.inf`
print(1 / arr)
```

In [6]:
print(1 / arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


```python
print(arr ** 3)
```

In [7]:
print(arr ** 3)

[  0   1   8  27  64 125 216 343 512 729]


### Numpy array methods

#### Sum of all elements in the numpy array
```python 
print(arr.sum())
```

In [8]:
print(arr.sum())

45


#### Mean of all elements in the numpy array
```python 
print(arr.mean())
```

In [9]:
print(arr.mean())

4.5


#### Standard deviation of all elements in the numpy array
```python 
print(arr.std())
```

In [10]:
print(arr.std())

2.8722813232690143


#### Variance or standard deviation squared of all elements in the numpy array
This tells us the spread of the values, or in other words how far each point is from each other in general

```python 
print(arr.var())
```


In [11]:
print(arr.var())

8.25
