# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

```python
import numpy as np
```

In [0]:
import numpy as np

```python
#Creating sample array
arr = np.array([1,2,3,4,5,6,7,8,9,10])

#Show
print(arr)
```

In [0]:
# Creating sample array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
 
# Show
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


<hr>
<br>
<br>

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

```python
#Get a value at an index
arr[8]
```

In [0]:
arr[8]

9

```python
#Get values in a range
print(arr[1:5])
```

In [0]:
print(arr[1:5])

[2 3 4 5]


<hr>
<br>
<br>

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

Broadcasting is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size.

[Article on numpy broadcasting](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/)

```python
print(arr)
```

In [0]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


```python
#Setting a value with index range (Broadcasting)
arr[0:5] = 100
print(arr)
```

In [0]:
arr[0:5] = 100
print(arr)

[100 100 100 100 100   6   7   8   9  10]


<br>

### Implications

```python
# Reset array, aka undo the last cell.
arr = np.arange(0,11)

#Show
print(arr)
```

In [0]:
arr = np.arange(0,11)

#Show
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


```python
# Grab a slice of array
slice_of_arr = arr[0:6]

#Show slice
print(slice_of_arr)
```

In [0]:
# Grab a slice of array
slice_of_arr = arr[0:6]

#Show slice
print(slice_of_arr)

[0 1 2 3 4 5]


```python
#Change Slice... [:] means ALL elements.
slice_of_arr[:] = 99

#Show Slice again
print(slice_of_arr)
```

In [0]:
#Change Slice... [:] means ALL elements.
slice_of_arr[:] = 99

#Show Slice again
print(slice_of_arr)

[99 99 99 99 99 99]


In [0]:
list = [1,2,3,4,5,6]
print(type(list))
new_list = list
print(new_list)
new_list[0] = 45
print(new_list)
print(list)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[45, 2, 3, 4, 5, 6]
[45, 2, 3, 4, 5, 6]


**Now note the changes also occur in our original array!** This is because we copied by reference and not by value. 

```python
print(arr)
```

In [0]:
print(arr)

[99 99 99 99 99 99  6  7  8  9 10]


**Data is not copied, it's a view of the original array! This avoids memory problems!**

```python
#To get a copy, we need to be explicit!
arr_copy = arr.copy()
print(arr_copy)
```

In [0]:
#To get a copy, we need to be explicit!
arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]


<hr>
<br>
<br>

## Selection

Let's briefly go over how to use boolean comparisons to select certain values.

Specifically for numpy there is another way to do list sub-setting by using an array of booleans.

Suppose you want to get all the values in the numpy array that fall under a particular condition for example if we are trying to identify all values in the array that are greater than a certain value or are even. 

**Let's harness the true power of numpy arrays, this will be used heavily in future lectures.**


**References:**
- [Numpy masking python data science handbook tutorial](https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html#Comparison-Operators-as-ufuncs)
- [Another Numpy masking tutorial](https://www.python-course.eu/numpy_masking.php)

##### Create an array holding numbers 1 through 10

```python
arr = np.arange(1,11)
print(arr)
```

In [0]:
import numpy as np
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


##### Create a boolean array that filters out all the values that are greater than the value `6` and then print that newly created array to see the results.

Typically when we create a boolean mask and we store it in a new variable we want to be as descriptive as possible. We want to name this variable based on the condition and precede the variable name with `is` to signify that it is a boolean mask containing values of only `true` or `false`

For example:


```python
is_greater_than_six = arr > 6
print(is_greater_than_six)
```

In [0]:
is_greater_than_six = arr > 6
print(is_greater_than_six)

[False False False False False False  True  True  True  True]


**What you see being returned is called a boolean series.** 

We can use this boolean series to now index the numpy array `arr` by passing this newly created numpy mask array called `is_greater_than_six` in between square brackets of the numpy array `arr` like so: ```arr[is_greater_than_six] ```


This will return an array of the same size if all values pass the conditional test or a smaller array because not all values passed the conditional test. 

```python
g_than_six = arr[is_greater_than_six]
print(g_than_six)
```

In [0]:
g_than_six = arr[is_greater_than_six]
print(g_than_six)

[ 7  8  9 10]
